server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://xinggaoya.com:3306/shiro_test?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: xinggaocode
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates

  redis:
    host: localhost
    port: 6379
    password: xinggaocode
